name = "DeepGaussianSPDEProcesses"
uuid = "7336226e-4303-4ac4-b7ea-9f8be3fa382d"
authors = ["Jack Muir <jmuir@caltech.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
